# cfn-cg-01-central-governance-base-stack.yaml
# stackName: cfn-cg-01-central-governance-base-stack

AWSTemplateFormatVersion: 2010-09-09
Description: This Stack is Central governance base stack - cfn-cg-01-central-governance-base-stack will be deployed in central governance account

Resources:
# IAM Roles and Policies 
  LakeformationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ml-governance-central-acct-lf-srv-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lakeformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  S3DataLakePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "S3DataLakePolicy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - s3:ListBucket
            Resource: '*'
      Roles: 
        - !Ref LakeformationServiceRole

  AthenaConsumerAssumeRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: AthenaConsumerAssumeRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: sts:AssumeRole
        Path: "/"
        ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonAthenaFullAccess

# SSM 
  SSMParameterLakeformationServiceRoleName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/ml-governance/roles/lakeformation/rolename"
      Type: String
      Value: !Ref LakeformationServiceRole

  SSMParameterLakeformationServiceRoleArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/ml-governance/roles/lakeformation/rolearn"
      Type: String
      Value: !GetAtt LakeformationServiceRole.Arn

# DataCatalog and Lakeformation
  BankDatabase:
    Type: AWS::Glue::Database
    Properties: 
      CatalogId: !Ref AWS::AccountId
      DatabaseInput: 
        Name:  bankdb

  CentralFeatureStoreDatabase:
    Type: AWS::Glue::Database
    Properties: 
      CatalogId: !Ref AWS::AccountId
      DatabaseInput: 
        Name: sagemaker_featurestore

  LFTagBank:
    DependsOn: BankDatabase
    Type: AWS::LakeFormation::Tag
    Properties: 
      CatalogId: !Ref AWS::AccountId
      TagKey: data
      TagValues: 
        - bank

  LFTagAssociationBank:
      DependsOn: 
        - LFTagBank
        - BankDatabase
      Type: AWS::LakeFormation::TagAssociation
      Properties:
        Resource:
          Database:
            CatalogId: !Ref AWS::AccountId
            Name: bankdb
        LFTags:
          - CatalogId: !Ref AWS::AccountId
            TagKey: data
            TagValues:
              - bank            
  
  LFTagAssociationCentralFeatureStoreDatabase:
      DependsOn: 
        - LFTagBank
        - CentralFeatureStoreDatabase
      Type: AWS::LakeFormation::TagAssociation
      Properties:
        Resource:
          Database:
            CatalogId: !Ref AWS::AccountId
            Name: sagemaker_featurestore
        LFTags:
          - CatalogId: !Ref AWS::AccountId
            TagKey: data
            TagValues:
              - bank    


Outputs:
  LakeformationServiceRoleName:
    Value: !Ref LakeformationServiceRole

  LakeformationServiceRoleArn:
    Value: !GetAtt LakeformationServiceRole.Arn

  SSMParameterLakeformationServiceRoleName:
    Value: !Ref SSMParameterLakeformationServiceRoleName

  SSMParameterLakeformationServiceRoleArn:
    Value: !Ref SSMParameterLakeformationServiceRoleArn