# datamesh-producer-610630631243-stack-central-feature-store-stack
AWSTemplateFormatVersion: 2010-09-09
Description: Central account Lake Formation setups for cross-account sharing scenario

Parameters:
  CentralFeatureStoreAWSAccount:
    Type: String
    Description: Central feature store account for sharing cross account access.
    Default: 658352330480 
    
  CentralFeatureStoreBucketName:
      Type: String
      Description: Central feature store account - Feature group data catalog bucket name.
      Default: central-featurestore-658352330480-us-east-1
      
  CentralFeatureStoreKMSKeyARN:
      Type: String
      Description: Central feature store KMS Key Arn (used for Feature group data catalog bucket).
      Default: arn:aws:kms:us-east-1:658352330480:key/b7eb302a-9ce6-434e-92b7-8e97eae3cab4

Resources:

  CentralFeatureStoreS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${CentralFeatureStoreBucketName}-s3-access-policy'
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - lakeformation:RegisterResource
            Resource: 
              - !Sub arn:${AWS::Partition}:s3:::${CentralFeatureStoreBucketName}
          -
            Effect: "Allow"
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource: 
              - !Sub arn:${AWS::Partition}:s3:::${CentralFeatureStoreBucketName}/*
          -
            Effect: "Allow"
            Action:
              - s3:ListBucket
            Resource: 
              - !Sub arn:${AWS::Partition}:s3:::${CentralFeatureStoreBucketName}
          -
            Effect: "Allow"
            Action:
              - s3:ListBucket
            Resource: '*'
      Roles: 
        # - !Ref LFRegisterLocationServiceRoleName
        - 'ml-governance-central-acct-lf-srv-role'

  CentralFeatureStoreKMSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${CentralFeatureStoreBucketName}-kms-access-policy'
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
            - kms:DescribeKey
            - kms:Encrypt
            - kms:Decrypt
            - kms:ReEncrypt*
            - kms:GenerateDataKey
            - kms:GenerateDataKeyWithoutPlaintext
            Resource: 
              - !Ref CentralFeatureStoreKMSKeyARN
      Roles: 
        # - !Ref LFRegisterLocationServiceRoleName
        - 'ml-governance-central-acct-lf-srv-role'

  LFDataLakeLocationBank:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn: !Sub arn:${AWS::Partition}:s3:::${CentralFeatureStoreBucketName}
      # RoleArn: !Ref LFRegisterLocationServiceRoleArn 
      RoleArn: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/ml-governance-central-acct-lf-srv-role'
      UseServiceLinkedRole: false
      
  LFDataLocationPermissionBank:
    DependsOn: LFDataLakeLocationBank
    Type: AWS::LakeFormation::Permissions
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !Ref CentralFeatureStoreAWSAccount
      Permissions: 
        - DATA_LOCATION_ACCESS
      PermissionsWithGrantOption: 
        - DATA_LOCATION_ACCESS
      Resource:
        DataLocationResource:
          S3Resource: !Sub arn:${AWS::Partition}:s3:::${CentralFeatureStoreBucketName}

  LFTagLevelPermissions:
    Type: AWS::LakeFormation::PrincipalPermissions
    Properties:
      Principal:
        DataLakePrincipalIdentifier: !Ref CentralFeatureStoreAWSAccount
      Resource:
        LFTag:
          CatalogId: !Ref AWS::AccountId
          TagKey: data
          TagValues: 
             - bank
      Permissions: 
            - DESCRIBE
            - ASSOCIATE
      PermissionsWithGrantOption: 
            - DESCRIBE
            - ASSOCIATE

  LFTagDataLakeTableLevelPermissions:
    Type: AWS::LakeFormation::PrincipalPermissions
    Properties:
      Principal:
        DataLakePrincipalIdentifier: !Ref CentralFeatureStoreAWSAccount
      Resource:
        LFTagPolicy:
          CatalogId: !Ref AWS::AccountId
          ResourceType: TABLE
          Expression:
          - TagKey: data
            TagValues:
            - bank
      Permissions: 
            - ALL
      PermissionsWithGrantOption: 
            - ALL

  LFTagDataLakeDBLevelPermissions:
    Type: AWS::LakeFormation::PrincipalPermissions
    Properties:
      Principal:
        DataLakePrincipalIdentifier: !Ref CentralFeatureStoreAWSAccount
      Resource:
        LFTagPolicy:
          CatalogId: !Ref AWS::AccountId
          ResourceType: DATABASE
          Expression:
          - TagKey: data
            TagValues:
            - bank
      Permissions: 
        - ALTER
        - CREATE_TABLE
        - DESCRIBE
      PermissionsWithGrantOption: 
        - ALTER
        - CREATE_TABLE
        - DESCRIBE
