AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ManagementAccountId:
    Type: String
    Description: Account ID of the Management Account

Resources: 
  RootRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              AWS: 
                - !Sub arn:${AWS::Partition}:iam::${ManagementAccountId}:role/service-role/AWSControlTowerAdmin
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSServiceCatalogAdminFullAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Path: "/"